# Generated by Django 4.2.25 on 2025-10-15 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppBaseConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('current_version_android', models.CharField(blank=True, max_length=8, null=True)),
                ('minimum_support_version_android', models.CharField(blank=True, max_length=8, null=True)),
                ('current_version_ios', models.CharField(blank=True, max_length=8, null=True)),
                ('minimum_support_version_ios', models.CharField(blank=True, max_length=8, null=True)),
                ('last_sync_time', models.DateTimeField(blank=True, null=True)),
                ('cron_start_time', models.DateTimeField(blank=True, null=True)),
                ('cron_end_time', models.DateTimeField(blank=True, null=True)),
                ('bypass_password', models.CharField(blank=True, default='Team@7', max_length=210, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserCredentialValidation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('mobile_number', models.CharField(blank=True, max_length=12, null=True)),
                ('mobile_otp', models.CharField(blank=True, max_length=8, null=True)),
                ('otp_expiry', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_otp_verified', models.BooleanField(default=False)),
                ('user_registation_status', models.IntegerField(default=0)),
                ('admin_registration_designation', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAuthentication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('mobile_otp', models.CharField(blank=True, max_length=8, null=True)),
                ('otp_expiry', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_client', models.BooleanField(default=False)),
                ('is_contractor', models.BooleanField(default=False)),
                ('is_jobseeker', models.BooleanField(default=False)),
                ('last_active_time', models.DateTimeField(blank=True, null=True)),
                ('user_registation_status', models.IntegerField(default=0)),
                ('admin_registration_designation', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
